### ISSUE TITLE
Improve the output format

### ISSUE THREAD

**Issue by Kyle-Verhoog** [Kyle-Verhoog/doxxie#18]
It would be nice to have the output format be more human readable.

@brettlangdon suggested something similar to a pyi file that would look more similar to the real code.

Right now one problem that comes to mind with this format is handling MRO for classes. This could be incorporated into the pyi/python style file by using comment annotations. Similar could be done for other types of API metadata if need-be

**Comment by Kyle-Verhoog** [comment]
For classes @yun-kim and I have found that we can do ClassVar to distinguish between class and instance attributes as per https://github.com/python/mypy/issues/1097

**Comment by Yun-Kim** [comment]
For reference: https://docs.python.org/3/library/typing.html#typing.ClassVar
